### ISSUE TITLE
Github instruction error?

### ISSUE THREAD

**Issue by leannmlindsey** [ramanathanlab/genslm#97]
**Describe the bug**
I downloaded your 25M pretrained model from globius.  It is named "patric_25m_epoch01-val_loss_0.57_bias_removed.pt"

Then I saved the model to my google drive and tried to follow the instructions to load it

model = GenSLM("genslm_25M_patric", model_cache_dir="/content/drive/MyDrive/MODELS/genSLM/")
model.eval()

and I am getting this error

NotImplementedError                       Traceback (most recent call last)
[<ipython-input-15-bde908ac2ffe>](https://localhost:8080/#) in <cell line: 6>()
      4 from genslm import GenSLM, SequenceDataset
      5 
----> 6 model = GenSLM("genslm_25M_patric", model_cache_dir="/content/drive/MyDrive/MODELS/genSLM/")
      7 model.eval()
      8 

1 frames
[/usr/local/lib/python3.10/dist-packages/genslm/inference.py](https://localhost:8080/#) in configure_model(self)
     93         if not weight_path.exists():
     94             # TODO: Implement model download
---> 95             raise NotImplementedError
     96         ptl_checkpoint = torch.load(weight_path, map_location="cpu")
     97         model.load_state_dict(ptl_checkpoint["state_dict"], strict=False)

NotImplementedError:

**To Reproduce**

**CODE:**
!pip install git+https://github.com/ramanathanlab/genslm
from google.colab import drive
drive.mount('/content/drive')
import torch
import numpy as np
from torch.utils.data import DataLoader
from genslm import GenSLM, SequenceDataset

model = GenSLM("genslm_25M_patric", model_cache_dir="/content/drive/MyDrive/MODELS/genSLM/")
model.eval()

**Expected behavior**
I expected this to load the model

**ERROR:**
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-15-bde908ac2ffe>](https://localhost:8080/#) in <cell line: 6>()
      4 from genslm import GenSLM, SequenceDataset
      5 
----> 6 model = GenSLM("genslm_25M_patric", model_cache_dir="/content/drive/MyDrive/MODELS/genSLM/")
      7 model.eval()
      8 

1 frames
[/usr/local/lib/python3.10/dist-packages/genslm/inference.py](https://localhost:8080/#) in configure_model(self)
     93         if not weight_path.exists():
     94             # TODO: Implement model download
---> 95             raise NotImplementedError
     96         ptl_checkpoint = torch.load(weight_path, map_location="cpu")
     97         model.load_state_dict(ptl_checkpoint["state_dict"], strict=False)

NotImplementedError:
**Screenshots**

**Environment (please complete the following information):**
 - Google Colab

**Additional context**
This is the same way that I use my google drive to upload and read other files with no issue, so I do not think it is a problem with the path.

**Comment by leannmlindsey** [comment]
Thanks for the help. Yes, it was a naming problem with the file.

**Comment by KPHippe** [comment]
Good to hear. Thanks!
